* Software fuer den SundialsNavigator (Stand: 6.6.2013)

** BasicTools (javascript)
   https://github.com/topoi/sundialsNavigator

*** 1.1 erster Filter filtert auf '&&' Basis zwischen drei Materialtypen und gibt Output in Konsole aus
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js
*** 1.2 Materialselektion: definiert ein Histogram mit den Haeufigkeiten, welches angeklickt werden kann
        https://github.com/topoi/sundialsNavigator/blob/master/Material.js
*** 1.3 Typselektion: definiert ein Histogram mit Hauefigkeiten, welches angeklickt werden kann
        https://github.com/topoi/sundialsNavigator/blob/master/Typ.js
*** 1.4 Datumselektion: definiert ein Histogra mit Haeufigkeiten, welches angeklickt werden kann
        https://github.com/topoi/sundialsNavigator/blob/master/Datum.js

** Alle div Elemente fuer die Identifizierung

*** 1.1 <div id="typ"></div><div id="typ"></div>
        https://github.com/topoi/sundialsNavigator/blob/master/Typ.js
*** 1.3 <div id="datum"></div><div id="datum"></div>
        https://github.com/topoi/sundialsNavigator/blob/master/datum.js
*** 1.4 <div id="material"></div><div id="material"></div>
        https://github.com/topoi/sundialsNavigator/blob/master/Material.js
*** 1.7 <div id="filterLogikMaterial"></div><div id="filterLogikMaterial"></div>
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js
*** 1.8 <div id="filterLogikDatum"></div><div id="filterLogikDatum"></div>
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js  
*** 1.8 <div id="filterLogikTyp"></div><div id="filterLogikTyp"></div>
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js

** Alle Funktionen mit Uebergabeparametern

*** 1.1 datumSelection(data)
        beinhaltet alle Parameter fuer die Selektion des Datums, die Inputdaten werden uebergeben
        https://github.com/topoi/sundialsNavigator/blob/master/Datum.js

*** 1.2 materialSelection(data)
        beinhaltet alle Parameter fuer die Selektion des Materials, die Inputdaten werden uebergeben
        https://github.com/topoi/sundialsNavigator/blob/master/Material.js

*** 1.3 typSelection(data)
        beinhaltet alle Parameter fuer die Selektion des Types, die Inputdaten werden uebergeben
        https://github.com/topoi/sundialsNavigator/blob/master/Typ.js

*** 1.4 filterLogicMaterial(checkMaterial, data, material)
        filtert die Materialeigenschaften, checkMaterial beinhaltet die (true,false) Aussage fuer jede einzelne
        Sonnenuhr. Daten werden uebergeben. Der Wert 'material' wird fuer console.log benoetigt.
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js

*** 1.5 filterLogicDatum(checkDatum, data, datum)
        filtert die Datumseigenschaften, checkDatum beinhaltet die (true,false) Aussage fuer jede einzelne
        Sonnenuhr. Daten werden uebergeben. Der Wert 'datum' wird fuer console.log benoetigt.
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js

*** 1.6 filterLogicTyp(checkTyp, data, typ)
        filtert die Typeigenschaften, checkTyp beinhaltet die (true,false) Aussage fuer jede einzelne
        Sonnenuhr. Daten werden uebergeben. Der Wert 'typ' wird fuer console.log benoetigt.
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js

*** 1.7 filterAll()
        Herzstueck der Datenselektion. Je nach Bedarf werden die einzelnen Filterkombinationen
        definiert.
        https://github.com/topoi/sundialsNavigator/blob/master/Filter.js 
